app/routes/search.py
import os, uuid, time
from datetime import datetime
from flask import (
    Blueprint, 
    request,
    render_template, 
    redirect, 
    url_for, 
    flash,  
    current_app as app
)
from werkzeug.utils import secure_filename
from sqlalchemy import func
from flask_sqlalchemy import SQLAlchemy
from db import db
from models import *

bp = Blueprint("search", __name__)

@bp.route("/search", methods=["GET"])
def search():
    page_title = "Ricerca"

    start = time.time()

    query = request.args.get("q", "").strip()

    if not query:
        return render_template("view/risultati_ricerca.html", title=page_title, query=None, results=[], time=time.time()-start)
    
    results = []

    def build_results(model, label, url_func):
        search_col = model.search_vector
        relevance = func.length(search_col) - func.length(func.replace(search_col, query, ""))
        matches = model.query.filter(search_col.ilike(f"%{query}%")) \
                             .add_columns(relevance.label("relevance")) \
                             .order_by(relevance.desc()) \
                             .all()
        
        for obj, relevance_score in matches:
            results.append({
                "tipo": label,
                "titolo": str(obj),
                "url": url_func(obj),
                "snippet": build_snippet(obj.search_vector, query),
                "score": relevance_score
            })

    def build_snippet(text, keyword):
        import re
        pattern = re.compile(re.escape(keyword), re.IGNORECASE)
        snippet = pattern.sub(r"<mark>\g<0></mark>", text)
        return snippet if len(snippet) < 500 else snippet[:497] + "..."
    
    build_results(SchedaUS, "Scheda US", lambda o: url_for("view.scheda", id=o.id))
    build_results(RepertoNotevoleUS, "Reperto", lambda o: url_for("view.reperto_notevole", id=o.id))
    build_results(Anagrafica, "Anagrafica", lambda o: url_for("view.visualizza_anagrafiche"))
    build_results(Localita, "Località", lambda o: url_for("view.visualizza_localita"))
    build_results(Ente, "Ente", lambda o: url_for("view.visualizza_enti"))

    results.sort(key=lambda r: r["score"], reverse=True)

    return render_template("view/risultati_ricerca.html", title=f"Risultati per {query}", query=query, results=results, time=time.time()-start)

app/routes/view.py
import os
from flask import (
    Blueprint, 
    render_template, 
    flash, 
    redirect, 
    url_for, 
    send_from_directory,
    Response,
    session,
    current_app as app
)
from sqlalchemy import *
from flask_sqlalchemy import SQLAlchemy
from models import *
from graphviz import Digraph

bp = Blueprint("view", __name__)

def build_table_for_reperti(record):
    headers = [
        "ID", "US", "Numero cassa", "Sito", "Data",
        "Materiale", "Descrizione", "Quantità", "Lavato", "Siglato",
        "Punto stazione totale", "Coordinate", "Note"
    ]
    rows = []
    for r in record:
        rows.append([
            f'<a href="{url_for("view.reperto_notevole", id=r.id)}">Reperto №{r.id}</a>',
            f'<a href="{url_for("view.scheda", id=r.scheda_us.id)}">US {r.scheda_us.num_us}</a>',
            r.numero_cassa,
            r.sito,
            r.data.strftime('%d/%m/%Y') if r.data else '',
            r.materiale,
            r.descrizione,
            r.quantita,
            "&#10004;" if r.lavato else "",
            "&#10004;" if r.siglato else "",
            r.punto_stazione_totale,
            f"{r.coord_x}, {r.coord_y}, {r.coord_z}" if r.coord_x and r.coord_y and r.coord_z else "Non presenti",
            r.note or "",
        ])
    return headers, rows

def build_table_for_schede(record):
    labels = {
        "si": "Sì",
        "no": "No",
        "integrale": "Integrale",
        "a_campione": "A campione"
    }
    
    headers = [
        "US", "Descrizione", "Località", "Ente responsabile", "Data", "Quadrato", "Settore", "Colore",
        "Composizione", "Consistenza", "Componenti organici", "Componenti inorganici", "Campionature", 
        "Flottazione", "Setacciatura", "Interpretazione", "Misure", "Note" 
    ]
        
    rows = []
    for r in record:
        rows.append([
            f'<a href="{url_for("view.scheda", id=r.id)}">US {r.num_us}</a>',
            r.descrizione,
            f"{r.localita.via} - {r.localita.citta}" if r.localita else "",
            r.ente_responsabile.nome if r.ente_responsabile else "",
            r.data.strftime('%d/%m/%Y') if r.data else '',
            r.quadrato,
            r.settore,
            r.colore,
            r.composizione,
            r.consistenza,
            r.comp_organici,
            r.comp_inorganici,
            "Sì" if r.campionature == True else "No",
            labels.get(r.flottazione, r.flottazione),
            labels.get(r.setacciatura, r.setacciatura),
            r.interpretazione,
            r.misure,
            r.note or ""
        ])
    return headers, rows

def build_table_for_ortofoto(record):
    headers = [
        "Descrizione", "Link", "US associate", "Data", "Operatore", "Completato", "Target", "Note"
    ]
        
    rows = []
    for r in record:        
        schede_us = r.schede_us
        us_list = ", ".join([f"<a href=\"{url_for('view.scheda', id=s.id)}\">US {s.num_us}</a>" for s in schede_us]) if schede_us else "N/D"

        operatore = Anagrafica.query.get(r.id_operatore)
        name_and_surname = f"{operatore.nome} {operatore.cognome}" if operatore else "N/A"

        rows.append([
            r.descrizione,
            f'<a href="{r.path_ortofoto}">Apri link</a>',
            us_list,
            r.data.strftime('%d/%m/%Y') if r.data else '',
            name_and_surname,
            "&#10004;" if r.completato else "",
            r.target,
            r.note
        ])
    return headers, rows

@bp.route("/manuale", methods=["GET"])
def visualizza_manuale():
    page_title = "Manuale"

    return render_template("view/manuale.html", title=page_title)

@bp.route("/visualizza_anagrafiche", methods=["GET"])
def visualizza_anagrafiche():
    page_title = "Anagrafiche"

    records = Anagrafica.query.order_by(Anagrafica.cognome.asc()).all()
    return render_template("view/visualizza_anagrafiche.html", records=records, title=page_title)

@bp.route("/visualizza_localita", methods=["GET"])
def visualizza_localita():
    page_title = "Località"

    records = Localita.query.all()
    return render_template("view/visualizza_localita.html", records=records, title=page_title)

@bp.route("/visualizza_enti", methods=["GET"])
def visualizza_enti():
    page_title = "Enti"

    records = Ente.query.order_by(Ente.nome.asc()).all()
    return render_template("view/visualizza_enti.html", records=records, title=page_title)

@bp.route("/visualizza_schede", methods=["GET"])
def visualizza_schede():
    page_title = "Schede US"
    view = session.get("default_view", "card")
    
    if view == "card":
        records = SchedaUS.query.order_by(SchedaUS.num_us.asc()).all()
        return render_template(
            "view/visualizza_schede.html", 
            records=records, 
            title=page_title)
    elif view == "grid":
        headers, rows = build_table_for_schede(SchedaUS.query.order_by(SchedaUS.num_us.asc()).all())
        return render_template(
            "view/visualizza_schede.html", 
            headers=headers,
            rows=rows, 
            title=page_title)

@bp.route("/scheda/<int:id>")
def scheda(id):
    # Fetch the scheda by ID
    scheda = SchedaUS.query.get(id)

    if scheda is None:
        flash("Scheda non trovata", "error")
        return redirect(url_for("main.scheda", title="Schede US"))

    rel_partenza = SeqFisica.query.filter(SeqFisica.id_seq_a == id).all()
    rel_arrivo = SeqFisica.query.filter(SeqFisica.id_seq_b == id).all()
    rel_strat_partenza = SeqStrat.query.filter(SeqStrat.id_seq_a == id).all()
    rel_strat_arrivo = SeqStrat.query.filter(SeqStrat.id_seq_b == id).all()

    foto = FotoUS.query.filter_by(id_scheda_us=id).all()
    reperti_notevoli = RepertoNotevoleUS.query.filter_by(id_scheda_us=id).all()

    page_title = f"Scheda US {scheda.num_us}"

    return render_template(
        "view/scheda_us.html", 
        scheda=scheda, 
        rel_partenza=rel_partenza, 
        rel_arrivo=rel_arrivo,
        rel_strat_partenza=rel_strat_partenza,
        rel_strat_arrivo=rel_strat_arrivo,
        foto=foto,
        reperti_notevoli=reperti_notevoli,
        title=page_title
    )

@bp.route("/visualizza_reperti_notevoli", methods=["GET"])
def visualizza_reperti_notevoli():
    page_title = "Reperti notevoli"

    reperti_notevoli = RepertoNotevoleUS.query.order_by(RepertoNotevoleUS.id_scheda_us.asc()).all()
    headers, rows = build_table_for_reperti(reperti_notevoli)
    
    return render_template(
        "view/visualizza_reperti_notevoli.html", 
        headers=headers,
        rows=rows, 
        title=page_title
        )

@bp.route("/reperto_notevole/<int:id>")
def reperto_notevole(id):
    # Fetch the scheda by ID
    reperto = RepertoNotevoleUS.query.get(id)
    
    if reperto is None:
        flash("Reperto non trovato", "error")
        return redirect(url_for("view.visualizza_reperti_notevoli", title="Reperti notevoli"))

    page_title = f"Reperto №{reperto.id}"

    return render_template(
        "view/reperto_notevole.html", 
        reperto=reperto,
        title=page_title
    )

@bp.route("/get/<path:filename>")
def photo(filename):
    photo_dir = app.config["UPLOAD_FOLDER"]
    return send_from_directory(photo_dir, filename)

@bp.route("/visualizza_ortofoto", methods=["GET"])
def visualizza_ortofoto():
    page_title = "Ortofoto"
    ortofoto = Ortofoto.query.order_by(Ortofoto.id.asc()).all()
    
    headers, rows = build_table_for_ortofoto(ortofoto)

    return render_template(
        "view/visualizza_ortofoto.html", 
        headers=headers,
        rows=rows, 
        title=page_title)

@bp.route("/genera_grafo_stratigrafico", methods=["GET"])
def genera_grafo():
    # 1) crea il Digraph top-down
    dot = Digraph('Stratigrafia', format='svg', engine='dot')
    dot.graph_attr.update({
        'rankdir': 'TB',
        'splines': 'true',
        'overlap': 'false',
        'bgcolor': 'transparent',
    })
    dot.node_attr.update({
        'shape': 'box',
        'style': 'filled,rounded',
        'fillcolor': '#f9f9f9',
        'color': '#666666',
        'fontname': 'Helvetica',
        'fontsize': '12',
    })
    dot.edge_attr.update({
        'color': '#666666',
        'arrowsize': '0.8',
        'penwidth': '1',
        'fontname': 'Helvetica',
        'fontsize': '9',
    })

    # 2) relazioni e ID coinvolti
    rels = SeqStrat.query.all()
    coinvolti = {r.id_seq_a for r in rels} | {r.id_seq_b for r in rels}

    # 3) carica solo le SchedaUS coinvolte
    schede = SchedaUS.query.filter(SchedaUS.id.in_(list(coinvolti))).all()
    info_map = {s.id: (s.num_us, s.descrizione or "") for s in schede}

    # 4) nodi con link e tooltip
    for id_us in sorted(coinvolti):
        num, desc = info_map[id_us]
        href = url_for('view.scheda', id=id_us)
        label = f"US {num}"
        dot.node(
            str(id_us),
            label=label,
            href=href,
            tooltip=desc,
            target="_self"   # o "_blank" per aprire in nuova scheda
        )

    # 5) archi
    for r in rels:
        if r.id_seq_a in info_map and r.id_seq_b in info_map:
            dot.edge(
                str(r.id_seq_a),
                str(r.id_seq_b)
            )

    # 6) esporta SVG
    svg = dot.pipe().decode('utf-8')
    return Response(svg, mimetype='image/svg+xml')

@bp.route("/grafo_stratigrafico", methods=["GET"])
def visualizza_grafo():
    page_title = "Grafo stratigrafico"

    rels = SeqStrat.query.all()
    if not rels:
        return render_template(
            "view/grafo_stratigrafico.html", 
            title=page_title,
            grafo_svg=None
        )

    svg = genera_grafo().get_data(as_text=True)
    return render_template(
        "view/grafo_stratigrafico.html", 
        title=page_title,
        grafo_svg=svg
        )

app/templates/anagrafica.html
{% include 'header.html' %}
    <div class="container">
        {% include 'notifications.html' %}

        <h1>Nuova anagrafica</h1>

        <form method="POST">
            <label>Nome: <input type="text" name="nome" required></label><br>
            <label>Cognome: <input type="text" name="cognome" required></label><br>
            <label>Email: <input type="email" name="email" required></label><br>
            <label>Telefono: <input type="text" name="tel" required></label><br>
            <button type="submit">Aggiungi</button>
        </form>
    </div>
    
    {% include 'footer.html' %}
</html>

app/templates/ente.html
{% include 'header.html' %}
    <div class="container">
        {% include 'notifications.html' %}

        <h1>Nuovo ente</h1>

        <form method="POST">
            
            <label>Nome: <input type="text" name="nome" required></label><br>
            <label>Telefono: <input type="text" name="tel"></label><br>
            <label>Email: <input type="email" name="email"></label><br>
            
            <div class="form-widget-group">
            <label>Località: 
                <select name="id_loc" id="localita" required>
                    {% for loc in lista_localita %}
                        <option value="{{ loc.id }}">{{ loc.denom }} - {{ loc.via }}, {{ loc.citta }}</option>
                    {% endfor %}
                </select></label>
            </div>

            <a href="{{ url_for('create.nuova_localita') }}" class="button-link">Crea nuova località</a><br><br>
            
            <button type="submit">Aggiungi</button>

        </form>
    </div>

    {% include 'footer.html' %}
</html>

app/templates/footer.html
<script src="{{ url_for('static', filename='scripts.js') }}"></script>
<script src="{{ url_for('static', filename='vanilla-datatables.js') }}"></script>

<script>
        var dataTable = new simpleDatatables.DataTable("#interactive-table", {
            perPage: 10,
            perPageSelect: [5, 10, 25, 50],
            labels: {
                placeholder: "Filtra...",
                perPage: "elementi per pagina",
                noRows: "Nessun record trovato",
                info: "Mostra {start}–{end} di {rows} record"
            }
        });
</script>

<footer>
<div>
    <p>
        Archeo - versione 0.5.0a<br>
        Sviluppato da: <a href="https://www.bughunter.me">Andrey Snigirev</a><br>
        Copyright © 2025 Andrey Snigirev<br>
    </p>
</div>
</footer>
</body>

app/templates/header.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='vanilla-datatables.css') }}">
    <title>{{ title }} | Archeo</title>
</head>

<body>
  <header>
    <nav>
      <ul>
        <li><a href="{{ url_for('main.index') }}">Archeo</a></li>
        
        <li class="dropdown">
          <a href="#" class="dropbtn">Crea</a>
          <ul class="dropdown-content">
            <li><a href="{{ url_for('create.nuova_anagrafica') }}">Anagrafica</a></li>
            <li><a href="{{ url_for('create.nuova_localita') }}">Località</a></li>
            <li><a href="{{ url_for('create.nuovo_ente') }}">Ente</a></li>
            <li><a href="{{ url_for('create.nuova_scheda_us') }}">Scheda US</a></li>
            <li class="separator"></li>
            <li><a href="{{ url_for('create.nuova_ortofoto') }}">Ortofoto</a></li>
            <li><a href="{{ url_for('create.nuovo_reperto_notevole') }}">Reperto notevole</a></li>
            <li><a href="{{ url_for('create.nuovo_sacchetto_materiali') }}">Sacchetto materiali</a></li>
            <li><a class="disabled" href="#">Cassa materiali</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropbtn">Esplora</a>
          <ul class="dropdown-content">
            <li><a href="{{ url_for('view.visualizza_anagrafiche') }}">Anagrafiche</a></li>
            <li><a href="{{ url_for('view.visualizza_localita') }}">Località</a></li>
            <li><a href="{{ url_for('view.visualizza_enti') }}">Enti</a></li>
            <li><a href="{{ url_for('view.visualizza_schede') }}">Schede US</a></li>
            <li class="separator"></li>
            <li><a href="{{ url_for('view.visualizza_ortofoto') }}">Ortofoto</a></li>
            <li><a href="{{ url_for('view.visualizza_reperti_notevoli') }}">Reperti notevoli</a></li>
            <li><a class="disabled" href="#">Sacchetti materiali</a></li>
            <li><a class="disabled" href="#">Casse materiali</a></li>
            <li class="separator"></li>
            <li><a href="{{ url_for('view.visualizza_grafo') }}">Harris matrix</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropbtn">Modifica</a>
          <ul class="dropdown-content">
            <li><a href="{{ url_for('create.nuova_sequenza_fisica') }}">Sequenze fisiche</a></li>
            <li><a href="{{ url_for('create.nuova_sequenza_stratigrafica') }}">Sequenze stratigrafiche</a></li>
            <li><a class="disabled" href="#">Ortofoto</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropbtn">Debug</a>
          <ul class="dropdown-content">
            <li><a href="{{ url_for('main.initdb') }}">Inizializza database</a></li>
            <li><a href="{{ url_for('main.dumpdb') }}">Dump database</a></li>
            <li><a href="{{ url_for('main.create_dummy_data') }}">Crea dei dati di prova</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropbtn">Aiuto</a>
          <ul class="dropdown-content">
            <li><a href="{{ url_for('view.visualizza_manuale') }}">Manuale</a></li>
            <li class="separator"></li>
            <li><a class="disabled" href="#">Informazioni su Archeo</a></li>
          </ul>
        </li>

        <!-- Barra di ricerca -->
        <li class="search">
          <form action="{{ url_for('search.search') }}" method="get">
            <input type="text" name="q" minlength="3" placeholder="Cerca schede, località, descrizione…">
            <button type="submit">🔍</button>
          </form>
        </li>
      </ul>
    </nav>
  </header>

app/templates/index.html
{% include 'header.html' %}

    <section class="hero" style="background-image: url('{{ url_for('static', filename='img/hero-bg.jpg') }}');">
        <div class="hero-overlay"></div>
        <div class="hero-content">
            <h1>Archeo</h1>
            <p>Gestisci e documenta i tuoi scavi archeologici in modo semplice ed intuitivo.</p>
            <form action="{{ url_for('search.search') }}" method="get" class="hero-search">
                <input type="text" name="q" placeholder="Cerca schede, località, descrizione…" />
                <button type="submit">🔍</button>
            </form>
        </div>
        </div>
    </section>

    <div class="container">
        {% include 'notifications.html' %}

        <h2>Panoramica database</h2>

        <ul class="card-container">
            <li class="card card--flex">
                <img src="{{ url_for('static', filename='img/person.png') }}" class="card-img">
                <div class="card-info">
                    <h3>Anagrafiche</h3>
                    {{ count_anagrafiche or "N/A" }}
                </div>
            </li>

            <li class="card card--flex">
                <img src="{{ url_for('static', filename='img/building.png') }}" class="card-img">
                <div class="card-info">
                    <h3>Enti</h3>
                    {{ count_enti or "N/A" }}
                </div>
            </li>

            <li class="card card--flex">
                <img src="{{ url_for('static', filename='img/document.png') }}" class="card-img">
                <div class="card-info">
                    <h3>Schede US registrate</h3>
                    {{ count_us or "N/A" }}
                </div>
            </li>

            <li class="card card--flex">
                <img src="{{ url_for('static', filename='img/gem.png') }}" class="card-img">
                <div class="card-info">
                    <h3>Reperti registrati</h3>
                    {{ count_reperti or "N/A" }}
                </div>
            </li>

            <li class="card card--flex">
                <img src="{{ url_for('static', filename='img/bag.png') }}" class="card-img">
                <div class="card-info">
                    <h3>Sacchetti materiali</h3>
                    {{ count_sacchetti or "N/A" }}
                </div>
            </li>

            <li class="card card--flex">
                <img src="{{ url_for('static', filename='img/crate.png') }}" class="card-img">
                <div class="card-info">
                    <h3>Casse materiali</h3>
                    {{ count_casse_materiali or "N/A" }}
                </div>
            </li>
        </ul>
    </div>

    {% include 'footer.html' %}
</html>

app/templates/localita.html
{% include 'header.html' %}
    <div class="container">
        {% include 'notifications.html' %}

        <h1>Nuova località</h1>
        <form method="POST">
            <label>Denominazione: <input type="text" name="denominazione"></label><br>
            <label>Via: <input type="text" name="via" required></label><br>
            <label>Città: <input type="text" name="citta" required></label><br>
            <label>Provincia: <input type="text" name="provincia" required></label><br>
            <label>CAP: <input type="number" name="cap" required></label><br>
            <button type="submit">Aggiungi</button>
        </form>
    </div>

    {% include 'footer.html' %}
</html>

app/templates/notifications.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="notifications">
      <ul class="flashes">
        {% for category, message in messages %}
          <li class="{{ category }}">
            <span class="message">{{ message }}</span>
          </li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}
{% endwith %}

app/templates/view_scheda.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Visualizza Scheda</title>
</head>

{% include 'header.html' %}

<body>
    <div class="container">
        <h1>Dettagli Scheda US</h1>
        
        <table class="scheda-us" style="undefined;table-layout: fixed; width: 1020px"><colgroup>
            <col style="width: 170px">
            <col style="width: 170px">
            <col style="width: 170px">
            <col style="width: 170px">
            <col style="width: 170px">
            <col style="width: 170px">
            </colgroup>
            <tbody>
              <tr>
                <td><strong>US</strong><br>{{ scheda.num_us }}<br></td>
                <td colspan="4"><strong>Ente responsabile</strong><br>{{ scheda.ente_responsabile.nome }}</td>
                <td>Data<br>{{ scheda.data.strftime('%d-%m-%Y') }}</td>
              </tr>            
              <tr>
                <td colspan="5"><strong>Località</strong><br>{{ scheda.localita.denom }}<br>{{ scheda.localita.via }}, {{ scheda.localita.cap }} - {{ scheda.localita.citta }} ({{ scheda.localita.provincia }})</td>
                <td colspan="1"><strong>Quadrato:</strong><br>{{ scheda.quadrato }}</td>
            </tr>
              <tr>
                <td colspan="6">
                    <strong>Modo di formazione</strong><br>{{ scheda.modo_formazione }}
                </td>
              </tr>
              <tr>
                <td colspan="3"><strong>Componenti organici</strong><br>{{ scheda.comp_organici }}</td>
                <td colspan="3"><strong>Componenti inorganici</strong><br>{{ scheda.comp_inorganici }} </td>
              </tr>
              <tr>
                <td colspan="2"><strong>Consistenza:</strong><br>{{ scheda.consistenza }}</td>
                <td colspan="2"><strong>Colore:</strong><br>{{ scheda.colore }}</td>
                <td colspan="2"><strong>Misure:</strong><br>{{ scheda.misure }}</td>
              </tr>
              <tr>
                <td colspan="6"><strong>Descrizione</strong><br>{{ scheda.descrizione }}</td>
              </tr>
              <tr>
                <td colspan="6"><strong>Note e osservazioni</strong><br>{{ scheda.note }}</td>
              </tr>
              <tr>
                <td colspan="6"><strong>Interpretazione</strong><br>{{ scheda.interpretazione }}</td>
              </tr>
              <tr>
                <td colspan="6"><strong>Elementi datanti</strong><br>{{ scheda.elem_datanti }}</td>
              </tr>
              <tr>
                <td colspan="3"><strong>Composizione</strong><br>{{ scheda.composizione }}</td>
                <td colspan="3"><strong>Elementi datanti</strong><br>{{ scheda.elem_datanti }}</td>
              </tr>
              <tr>
                <td colspan="2">
                    <strong>Campionature:</strong><br>{{ 'Sì' if scheda.campionature else 'No' }}
                </td>
                <td colspan="2">
                    <strong>Flottazione:</strong><br>{{ 'Sì' if scheda.flottazione else 'No' }}
                </td>
                <td colspan="2">
                    <strong>Setacciatura:</strong><br>{{ scheda.setacciatura }}
                </td>
              </tr>
              <tr>
                <td colspan="6"><strong>Affidabilità stratigrafica</strong><br>{{ scheda.affidabilita_strat }}</td>
              </tr>
              <tr>
                <td colspan="6"><strong>Responsabile</strong><br>{{ scheda.responsabile.nome }} {{ scheda.responsabile.cognome }}</td>
              </tr>
              <tr>
                <td colspan="6"><strong>Responsabile scientifico</strong><br>{{ scheda.responsabile_scientifico.nome }} {{ scheda.responsabile_scientifico.cognome }}</td>
              </tr>
            </tbody></table>

        <!--
        <p><strong>Path foto:</strong> {{ scheda.path_foto }}</p>
        <p><strong>Path ortofoto:</strong> {{ scheda.path_ortofoto }}</p>
        -->
        <h2>Relazioni di Sequenza</h2>
        
        <h3>Sequenze fisiche</h3>

        {% if rel_partenza or rel_arrivo %}
            <ul>
                {% if rel_partenza %}
                    {% for rel_p in rel_partenza %}
                        <li>
                            {% if rel_p.sequenza == "copre" %}
                                Copre {{ rel_p.id_seq_b }}
                            {% elif rel_p.sequenza == "taglia" %}
                                Taglia {{ rel_p.id_seq_b }}
                            {% elif rel_p.sequenza == "riempie" %}
                                Riempie {{ rel_p.id_seq_b }}
                            {% elif rel_p.sequenza == "si_appoggia_a" %}
                                Si appoggia a {{ rel_p.id_seq_b }}
                            {% elif rel_p.sequenza == "uguale_a" %}
                                Uguale a {{ rel_p.id_seq_b }}
                            {% elif rel_p.sequenza == "si_lega_a" %}
                                Si lega a {{ rel_p.id_seq_b }}
                            {% endif %}
                        </li>
                    {% endfor %}
                {% endif %}

                {% if rel_arrivo %}
                    {% for rel_a in rel_arrivo %}
                        <li>
                            {% if rel_a.sequenza == "copre" %}
                                Coperta da {{ rel_a.id_seq_a }}
                            {% elif rel_a.sequenza == "taglia" %}
                                Tagliata da {{ rel_a.id_seq_a }}
                            {% elif rel_a.sequenza == "riempie" %}
                                Riempita da {{ rel_a.id_seq_a }}
                            {% elif rel_a.sequenza == "si_appoggia_a" %}
                                Gli si appoggia {{ rel_a.id_seq_a }}
                            {% elif rel_a.sequenza == "uguale_a" %}
                                Uguale a {{ rel_a.id_seq_a }}
                            {% elif rel_a.sequenza == "si_lega_a" %}
                                Si lega a {{ rel_a.id_seq_a }}
                            {% endif %}
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        {% else %}
            <p>Nessuna sequenza fisica trovata.</p>
        {% endif %}
        
        <h3>Sequenze stratigrafiche</h3>

        {% if rel_strat_partenza or rel_strat_arrivo %}
        
            <ul>

            {% if rel_strat_partenza %}
                {% for rel in rel_strat_partenza %}
                    <li>
                        Posteriore a {{ rel.id_seq_b }}
                    </li>
                {% endfor %}
            {% endif %}

            {% if rel_strat_arrivo %}
                {% for rel in rel_strat_arrivo %}
                    <li>
                        Anteriore a {{ rel.id_seq_a }}
                    </li>
                {% endfor %}
            {% endif %}
            
            </ul>
        {% else %}
            <p>Nessuna sequenza stratigrafica trovata.</p>
        {% endif %}

        <a href="{{ url_for('main.scheda') }}">Torna alla lista</a>
        
    </div>

    {% include 'footer.html' %}
</body>
</html>